### ISSUE TITLE
Interface 'FileWithPath' incorrectly extends 'File'

### ISSUE THREAD

**Issue by yjkimjunior** [react-dropzone/file-selector#12] opened 2019-06-19 09:23 UTC
```
node_modules/file-selector/dist/file.d.ts:3:18 - error TS2430: Interface 'FileWithPath' incorrectly extends interface 'File'.
  Types of property 'path' are incompatible.
    Type 'string | undefined' is not assignable to type 'string'.
      Type 'undefined' is not assignable to type 'string'.

export interface FileWithPath extends File {
                   ~~~~~~~~~~~~
```

**Comment by johnryan** [comment] 2019-10-15 13:20
It looks like (in my case at least) this is caused by a conflicting type. I'm not sure if there's a way to specify that this is extending the `lib.dom.d.ts` definition rather than another.

**Comment by marcello3d** [comment] 2019-10-22 21:06
I am also hitting this problem when using `react-dropzone` with `electron` when I try to upgrade to TypeScript 3.6.4.

Electron extends File to always have a `path: string` parameter:
https://github.com/electron/typescript-definitions/blob/b970d51b347746cc0399db2d758e5c5b795d6787/base/base_footer.ts#L9

Error I get:
```
/Users/marcello/Documents/github/project/node_modules/file-selector/dist/file.d.ts
ERROR in /Users/marcello/Documents/github/project/node_modules/file-selector/dist/file.d.ts(3,18):
TS2430: Interface 'FileWithPath' incorrectly extends interface 'File'.
  Types of property 'path' are incompatible.
    Type 'string | undefined' is not assignable to type 'string'.
      Type 'undefined' is not assignable to type 'string'.
```

**Comment by yjkimjunior** [comment] 2019-10-22 21:20
what works for me is just locking my react-dropzone version to 10.17, and this seems so far to be in line with the DefinitelyTyped types. if and when this changes, i'll bump it.

**Comment by jwoo0122** [comment] 2020-04-29 06:56
Any update or solution about this typing problem?

**Comment by burtonator** [comment] 2020-06-23 20:16
Is everyone having this problem with Electron?  To be fair I think it's Electron's fault maybe?  I'm not sure if there's a way to say that something is JUST extended from 'dom' ... maybe import it as from 'dom' ??  I haven't tried that

**Comment by burtonator** [comment] 2020-06-23 22:02
There's a simple fix for this... 

```typescript
/** Provides information about files and allows JavaScript in a web page to access their content. */
interface DOMFile extends Blob {
    readonly lastModified: number;
    readonly name: string;
}

export interface FileWithPath extends DOMFile {
    readonly path?: string;
}
```

... this should work and avoid conflicts since typescript types are structural.  FileWithPath will be compatible with File from DOM as I lifted the interface for DOMFile right from their namespace.

**Comment by burtonator** [comment] 2020-06-23 22:04
Sent a PR for this:

https://github.com/react-dropzone/file-selector/pull/30

**Comment by JeromeLeLan** [comment] 2020-08-05 15:29
I got the same issue, using react-dropzone 11, Typescript, and Electron.

Any news about your PR being merged?

**Closed** 2020-08-07 02:46 UTC
